name: Github Actions for build LaTeX and release pdf
description: GitHub Action for build LaTeX and release pdf
author: MaineK00n
inputs:
  root:
    description: "github root_tex. this is require when comment is true."
    default: ""
    required: true
  token:
    description: "github token. this is require when comment is true."
    default: ""
    required: true
  repository:
    description: "github repository name. this is require when comment is true."
    default: ""
    required: true
  pdf_name:
    description: "release pdf name. this is require when comment is true."
    default: ""
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.root }}
    - ${{ inputs.token }}
    - ${{ inputs.repository }}
    - ${{ inputs.pdf_name }}
branding:
  icon: book
  color: blue
